add_subdirectory(core)
add_subdirectory(audio)
add_subdirectory(filesystem)
add_subdirectory(content)
add_subdirectory(json_support)
add_subdirectory(project)
if(CUEXIS_BUILD_SDL_ADAPTER)
    add_subdirectory(platform)
endif()
if(CUEXIS_BUILD_AUDIO_SDL_ADAPTER)
    add_subdirectory(audio_sdl)
endif()
add_subdirectory(world)
add_subdirectory(assets)
add_subdirectory(chart)
add_subdirectory(behavior)
add_subdirectory(gameplay)
add_subdirectory(render)
add_subdirectory(debug)
add_subdirectory(runtime)
if(CUEXIS_BUILD_OPENGL_ADAPTER)
    add_subdirectory(render_opengl)
endif()
add_subdirectory(playback)
