find_package(Catch2 3 CONFIG REQUIRED)

add_subdirectory(core)
add_subdirectory(audio)
add_subdirectory(filesystem)
add_subdirectory(content)
add_subdirectory(json_support)
add_subdirectory(project)
if(TARGET cuexis_platform_sdl)
    add_subdirectory(platform)
endif()
if(TARGET cuexis_audio_sdl)
    add_subdirectory(audio_sdl)
endif()
add_subdirectory(assets)
add_subdirectory(chart)
add_subdirectory(cxc)
add_subdirectory(behavior)
add_subdirectory(gameplay)
add_subdirectory(debug)
add_subdirectory(render)
add_subdirectory(runtime)
add_subdirectory(world)
add_subdirectory(playback)
add_subdirectory(presentation)
add_subdirectory(cfu_f)
if(TARGET cuexis_player)
    add_subdirectory(player)
endif()
